apiVersion: v1
kind: Pod
metadata:
  name: your-pod
spec:
  containers:
  - name: your-container
    image: your-app-image
    # your container configuration here
  initContainers:
  - name: init-container-1
    image: your-init-container-image-1
    command: ["/bin/sh", "-c", "echo 'Init Container 1'"]
  - name: init-container-2
    image: your-init-container-image-2
    command: ["/bin/sh", "-c", "echo 'Init Container 2'"]
